apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: o2
  name: local-path-pvc-redis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: o2
  name: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        volumeMounts:
        - name: redis-storage
          mountPath: /data/redis
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: 250m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 1Gi
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: local-path-pvc-redis
---
apiVersion: v1
kind: Service
metadata:
  namespace: o2
  name: redis
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: http
  selector:
    app: redis
---
# Удалить при переезде на k8s
apiVersion: v1
kind: Service
metadata:
  namespace: o2
  name: o2-redis
spec:
  ports:
    - name: o2-redis
      nodePort: 32379
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis
  type: NodePort