apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: o2
  name: web
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: maprox/o2-web
        env:
        - name: SRV_RUN
          value: WWW
        - name: AMQP_HOST
          value: rabbitmq
        - name: AMQP_PORT
          value: "5672"
        - name: AMQP_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: rabbitmq-user
        - name: AMQP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: rabbitmq-password
        - name: DB_HOST
          value: postgres
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres
              key: database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: HOST_NAME
          value: observer.maprox.net
        #   valueFrom:
        #     secretKeyRef:
        #       name: web
        #       key: HOST_NAME
        # - name: HOST_STATIC
        #   valueFrom:
        #     secretKeyRef:
        #       name: web
        #       key: HOST_STATIC
        # - name: JASPER_URL
        #   valueFrom:
        #     secretKeyRef:
        #       name: web
        #       key: JASPER_URL
        # - name: KEY_SALT
        #   valueFrom:
        #     secretKeyRef:
        #       name: web
        #       key: KEY_SALT
        # - name: NODE_HOST
        #   valueFrom:
        #     secretKeyRef:
        #       name: web
        #       key: NODE_HOST
        # - name: NODE_HOST_SSL
        #   valueFrom:
        #     secretKeyRef:
        #       name: web
        #       key: NODE_HOST_SSL
        # - name: OTHER_IP
        #   valueFrom:
        #     secretKeyRef:
        #       name: web
        #       key: OTHER_IP
        # - name: RBKM_IDSHOP
        #   valueFrom:
        #     secretKeyRef:
        #       name: web
        #       key: RBKM_IDSHOP
        # - name: RBKM_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: web
        #       key: RBKM_KEY
        # - name: RBKM_WALLET
        #   valueFrom:
        #     secretKeyRef:
        #       name: web
        #       key: RBKM_WALLET
        # - name: REGISTER_URL
        #   valueFrom:
        #     secretKeyRef:
        #       name: web
        #       key: REGISTER_URL
        # - name: SMSPILOT_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: web
        #       key: SMSPILOT_KEY
        # - name: SMSTEAM_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: web
        #       key: SMSTEAM_KEY
        # - name: SMSTEAM_LOGIN
        #   valueFrom:
        #     secretKeyRef:
        #       name: web
        #       key: SMSTEAM_LOGIN
        # - name: SMSTEAM_PASS
        #   valueFrom:
        #     secretKeyRef:
        #       name: web
        #       key: SMSTEAM_PASS
        # - name: SMTP_HOST
        #   valueFrom:
        #     secretKeyRef:
        #       name: web
        #       key: SMTP_HOST
        # - name: SMTP_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: web
        #       key: SMTP_PASSWORD
        # - name: SMTP_USERNAME
        #   valueFrom:
        #     secretKeyRef:
        #       name: web
        #       key: SMTP_USERNAME
        # - name: YM_ID
        #   valueFrom:
        #     secretKeyRef:
        #       name: web
        #       key: YM_ID
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 250m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: o2
  name: web
  labels:
    app: web
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: o2-web-ingress
  namespace: o2
spec:
  ingressClassName: nginx
  rules:
  - host: observer.maprox.net
    http:
      paths:
        - backend:
            service:
              name: web
              port:
                number: 80
          path: /
          pathType: Prefix
  tls:
  - hosts:
      - observer.maprox.net
    secretName: observer-maprox-net