apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: o2
  name: job-mon-ignition-check-onpacket
  labels:
    app: job-mon-ignition-check-onpacket
spec:
  selector:
    matchLabels:
      app: job-mon-ignition-check-onpacket
  template:
    metadata:
      labels:
        app: job-mon-ignition-check-onpacket
    spec:
      containers:
      - name: job-mon-ignition-check-onpacket
        image: maprox/o2-web
        env:
        - name: SRV_RUN
          value: JOB
        - name: JOB_START
          value: mon_ignition
        - name: JOB_KEY
          value: check.onpacket
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: job-config
              key: JOB_ENVIRONMENT
        - name: HOST_NAME
          valueFrom:
            configMapKeyRef:
              name: job-config
              key: JOB_HOSTNAME
        - name: AMQP_HOST
          value: rabbitmq
        - name: AMQP_PORT
          value: "5672"
        - name: AMQP_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: rabbitmq-user
        - name: AMQP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: rabbitmq-password
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres
              key: database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        resources:
          limits:
            cpu: 250m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 1Gi
