apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: o2
  name: job-mon-device-geofence-update-onpacket
  labels:
    app: job-mon-device-geofence-update-onpacket
spec:
  selector:
    matchLabels:
      app: job-mon-device-geofence-update-onpacket
  template:
    metadata:
      labels:
        app: job-mon-device-geofence-update-onpacket
    spec:
      containers:
      - name: job-mon-device-geofence-update-onpacket
        image: maprox/observer-job-geofence-presence
        env:
        - name: AMQP_HOST
          value: rabbitmq
        - name: AMQP_PORT
          value: "5672"
        - name: AMQP_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: rabbitmq-user
        - name: AMQP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: rabbitmq-password
        - name: AMQP_EXCHANGE
          value: mon.device
        - name: AMQP_QUEUE_NAME
          value: prod.mon.device.geofence.update.onpacket
        - name: AMQP_QUEUE_ROUTING_KEY
          value: prod.mon.device.geofence.update.onpacket
        - name: AMQP_OUTBOUND_EXCHANGE
          value: x.notification
        - name: AMQP_OUTBOUND_ROUTING_KEY
          value: prod.x.notification.notification.process.onpacket
        - name: AMQP_MESSAGES_COUNT_LIMIT
          value: "10"
        - name: PGHOST
          value: postgres
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              name: postgres
              key: database
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: postgres
              key: user
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
        resources:
          limits:
            cpu: 250m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 1Gi
